# Generated by Django 5.2.12 on 2026-03-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_create_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructor_name', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(max_length=32)),
            ],
        ),
    ]
